name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install python-setuptools git build-essential ninja-build cmake libsdl2-dev qtbase5-dev libqt5opengl5-dev qtwebengine5-dev qtbase5-private-dev python python3-pip libboost-dev libboost-context-dev libzip-dev liblz4-dev libmbedtls-dev libssl-dev libopus-dev zlib1g-dev libzstd-dev
        pip3 install --user conan
        sudo -E ln -s ~/.local/bin/conan /usr/bin/conan
    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -GNinja
        ninja
        sudo ninja install
    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      with:
        name: aa
        path: ss
